version: "3.8"

services:
  postgres:
    image: postgres
    # environment:
    #   POSTGRES_DB: ${POSTGRES_APPLICATION_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
    ports:
      - "27017:27017"
